"""Hand-rolled pure-JAX SG-MCMC updates (no blackjax dependency).

These reproduce the math of the original csgmcmc PyTorch code
(``experiments/cifar_csgmcmc.py`` / ``cifar_csghmc.py``) directly.

  * SGLD : position += step_size * g + sqrt(2 * temperature * step_size) * noise
           -- identical to blackjax's overdamped Langevin, so given the same
           rng_key the two SGLD backends agree to floating-point tolerance.
  * SGHMC: buf = (1 - alpha) * buf + step_size * g
                 + sqrt(2 * alpha * temperature * step_size) * noise
           position += buf
           -- the original's ``(1 - alpha)`` momentum-buffer form (``alpha`` is
           "one minus momentum", e.g. 0.9), distinct from blackjax's friction
           parameterization.

``g`` is the log-posterior gradient (ascent direction); the driver forms it as
``g = -(grad_loss + weight_decay * position)``.

Noise is generated by raveling the pytree and drawing a single flat normal, which
matches ``blackjax.util.generate_gaussian_noise`` so the SGLD backends coincide.
"""

import jax
import jax.numpy as jnp
from jax.flatten_util import ravel_pytree


def _gaussian_like(rng_key, position):
    flat, unravel = ravel_pytree(position)
    sample = jax.random.normal(rng_key, shape=flat.shape, dtype=flat.dtype)
    return unravel(sample)


def make_sgld():
    def step(rng_key, position, g, step_size, temperature):
        noise = _gaussian_like(rng_key, position)
        scale = jnp.sqrt(2.0 * temperature * step_size)
        return jax.tree_util.tree_map(
            lambda p, gg, n: p + step_size * gg + scale * n,
            position,
            g,
            noise,
        )

    return step


def make_sghmc(alpha=0.9, beta=0.0):
    """Original csgmcmc SGHMC. ``alpha`` is ``1 - momentum`` (``beta`` unused; kept
    for interface symmetry with the blackjax backend)."""
    del beta

    def step(rng_key, position, momentum, g, step_size, temperature):
        noise = _gaussian_like(rng_key, position)
        scale = jnp.sqrt(2.0 * alpha * temperature * step_size)
        momentum = jax.tree_util.tree_map(
            lambda buf, gg, n: (1.0 - alpha) * buf + step_size * gg + scale * n,
            momentum,
            g,
            noise,
        )
        position = jax.tree_util.tree_map(lambda x, buf: x + buf, position, momentum)
        return position, momentum

    return step
